runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: ssl
  version: latest

handlers:
- url: .*
  script: main.app

env_variables:
  token: 'insert token of your bot'
  hook: '/incoming'
