version: '2'

services:
  tlm_bot_backend:
    build: '.'
    image: 'vshevchenko/tlm_bot_backend'
    environment:
      - token=in_docker-compose.dev.yml
    ports:
      - 8080:8080
    entrypoint: python
    command: 'main.py'
    depends_on:
      - db
      - redis
    logging:
      driver: 'journald'
    restart: always

  db:
    image: 'postgres:9.6'
    ports:
      - '5432:5432'
      # TODO: '127.0.0.1:5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data/'

  redis:
    image: 'redis'
    ports:
        # TODO: '127.0.0.1:6379:6379'
      - '6379:6379'
    volumes:
      - 'redis_data:/data'

  celery_worker:
    build: '.'
    image: 'vshevchenko/tlm_bot_backend'
    command: celery -E -A backgrounds.celery worker -l debug
    # TODO: need to override expose ports from Dockerfile
    depends_on:
      - redis

volumes:
  pg_data:
  redis_data:
